### ISSUE TITLE
Include header ids when importing information from terms

### ISSUE THREAD

**Issue by sih** [trustoverip/ctwg-toolkit-mrg#5]
@RieksJ should all headings be included? Even headings that seem HRG specific (e.g. Dockusaurus headings)

**Comment by RieksJ** [comment]
Strictly speaking only TEv2 headers should suffice. Lets stick to that so we can experience if we need more.

**Comment by RieksJ** [comment]
Note that different types of terminological artifacts have header parts that differ. We may need a means to allow curators to define different types of such artifacts with different header fields, perhaps in config-file-like things, so that the tool doesn't have to be revised to accommodate for such things.

**Comment by sih** [comment]
Ok sure ... I'll begin with the basic assumption as above and then once you're back from holidays we can refine it (assuming that I get to this issue before you return!
